---

- debug: msg='1.2.1 Ensure package manager repositories are configured (Not Scored)'
  tags:
    - notscored
    - 1.2.1

- debug: msg='1.2.2 Ensure GPG keys are configured (Not Scored)'
  tags:
    - notscored
    - 1.2.2
