---

# 1.3.1 Ensure AIDE is installed (Scored)
- name: Install aide
  apt:
    name: aide
    state: present
  when: "'1.3.1' not in os_hardening_exclusions"
  tags: [ scored, 1.3.1 ]

# 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
- name: Create cron job for regular aide check
  cron:
    name:       "AIDE Check"
    user:       root
    hour:       "5"
    job:        "/usr/bin/aide --check"
    state:      present
  when: "'1.3.2' not in os_hardening_exclusions"
  tags: [ scored, 1.3.2 ]
