---

# 1.8 Ensure updates, patches, and additional security software are installed (Not Scored)

- name: Ensure updates, patches, and additional security software are installed
  apt:
    update_cache:
    upgrade: dist
  when: "'1.8' not in os_hardening_exclusions and os_hardening_dist_upgrade"
  tags:
    - notscored
    - "1.8"
