---
## 3.6.1 Ensure iptables is installed (Scored)
- name: Install iptables
  apt:
    name:  iptables
    state: present

## 3.6.2 Ensure default deny firewall policy (Scored)
# iptables -P INPUT DROP
# iptables -P OUTPUT DROP
# iptables -P FORWARD DROP
## WARNING: Changing firewall settings while connected over network can result
##          in being locked out of the system.
##          Do NOT do it, you most CERTAINLY will be locked out !!!
#- name: Configure default deny firewall policy
#  iptables:
#    chain: "{{ item }}"
#    jump:  DROP
#  with_items:
#    - INPUT
#    - FORWARD
#    - OUTPUT

## 3.6.3 Ensure loopback traffic is configured (Scored)
# iptables -A INPUT -i lo -j ACCEPT
# iptables -A OUTPUT -o lo -j ACCEPT
# iptables -A INPUT -s 127.0.0.0/8 -j DROP
- name: Accept loopback traffic on IN interface
  iptables:
    action: append
    chain:  INPUT
    jump:   ACCEPT
    in_interface: lo
- name: Accept loopback traffic on OUT interface
  iptables:
    action: append
    chain:  OUTPUT
    jump:   ACCEPT
    in_interface: lo
- name: Drop traffic from source 127.0.0.0/8
  iptables:
    action: append
    chain:  INPUT
    jump:   DROP
    source: "127.0.0.0/8"

## 3.6.4 Ensure outbound and established connections are configured (Not Scored)
# iptables -A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
# iptables -A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
# iptables -A OUTPUT -p icmp -m state --state NEW,ESTABLISHED -j ACCEPT
# iptables -A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
# iptables -A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
# iptables -A INPUT -p icmp -m state --state ESTABLISHED -j ACCEPT
- name: Allow outbound new and established connections
  iptables:
    action: append
    chain:  OUTPUT
    jump:   ACCEPT
    ctstate: 'NEW,ESTABLISHED'
    protocol: "{{ item }}"
  with_items: [ tcp, udp, icmp ]
- name: Allow inbound established connections
  iptables:
    action: append
    chain:  INPUT
    jump:   ACCEPT
    ctstate: 'ESTABLISHED'
    protocol: "{{ item }}"
  with_items: [ tcp, udp, icmp ]

## 3.6.5 Ensure firewall rules exist for all open ports (Scored)
## iptables -A INPUT -p <protocol> --dport <port> -m state --state NEW -j ACCEPT
## Hmmm... I wonder if this implies keeping an inventory of listening ports per
## host within a datacenter so as to add a rule for each one.
## How is this practical to manage? Seems like a unnecessary overhead
