---

# 5.4.1.1 Ensure password expiration is 90 days or less (Scored)
- name: Ensure password expiration is 90 days or less
  lineinfile:
    path: /etc/login.defs
    regexp: '^(PASS_MAX_DAYS).*'
    line:   '\1   90'
    backrefs: yes
  when: "'5.4.1.1' not in os_hardening_exclusions"
  tags: [ scored, '5.4.1.1' ]

# 5.4.1.2 Ensure minimum days between password changes is 7 or more (Scored)
- name: Ensure minimum days between password changes is 7 or more
  lineinfile:
    path: /etc/login.defs
    regexp: '^(PASS_MIN_DAYS).*'
    line:   '\1   7'
    backrefs: yes
  when: "'5.4.1.2' not in os_hardening_exclusions"
  tags: [ scored, '5.4.1.2' ]

# 5.4.1.3 Ensure password expiration warning days is 7 or more (Scored)
- name: Ensure password expiration warning days is 7 or more
  lineinfile:
    path: /etc/login.defs
    regexp: '^(PASS_WARN_AGE).*'
    line:   '\1   7'
    backrefs: yes
  when: "'5.4.1.3' not in os_hardening_exclusions"
  tags: [ scored, '5.4.1.3' ]

# 5.4.1.4 Ensure inactive password lock is 30 days or less (Scored)
# Remediation:
#   - Run the following command to set the default password inactivity period to 30 days:
#     # useradd -D -f 30
#   - Modify user parameters for all users with a password set to match:
#     # chage --inactive 30 <user>
# Tread carefully!
- name: Set the default password inactivity period to 30 days
  command: useradd -D -f 30
  changed_when: False
  when: "'5.4.1.4' not in os_hardening_exclusions"
  tags: [ scored, '5.4.1.4' ]

# 5.4.2 Ensure system accounts are non-login (Scored)
- name: Get system accounts with interactive shell configured
  shell: |
      egrep -v "^\+" /etc/passwd | awk -F: '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="vagrant" && \
      $1!="halt" && $3<1000 && $7!="/usr/sbin/nologin" && $7!="/bin/false") {print $1}'
  register: system_accounts
  changed_when: False

- name: Set shell of system accounts to /usr/sbin/nologin
  command: usermod -s /usr/sbin/nologin {{ item }}
  with_items: "{{ system_accounts.stdout_lines }}"
  when: "'5.4.2' not in os_hardening_exclusions"
  tags: [ scored, '5.4.2' ]

# 5.4.3 Ensure default group for the root account is GID 0 (Scored)
- name: Ensure default group for the root account is GID 0
  user:
    name:  root
    group: root
  when: "'5.4.3' not in os_hardening_exclusions"
  tags: [ scored, '5.4.3' ]

# 5.4.4 Ensure default user umask is 027 or more restrictive
- name: Ensure default user umask is 027 or more restrictive
  lineinfile:
    path: "{{ item }}"
    line:   'umask 027'
  with_items:
    - /etc/bash.bashrc
    - /etc/profile
  when: "'5.4.4' not in os_hardening_exclusions"
  tags: [ scored, '5.4.4' ]
