---

# 5.6 Ensure access to the su command is restricted (Scored)
- name: Ensure access to the su command is restricted
  lineinfile:
    path: /etc/pam.d/su
    regexp: '^#\s+(auth\s+required\s+pam_wheel.so)$'
    line:   '\1 use_uid'
    backrefs: yes
  when: "'5.6' not in os_hardening_exclusions"
  tags: [ scored, '5.6' ]
