---

- debug: msg="Ensure {{ svc_item.name }} is not enabled"

- name: Check if {{ svc_item.script }} exists
  stat:
    path: "{{ svc_item.script }}"
  when: svc_item.cis_id not in os_hardening_exclusions
  register: svc
  tags:
    - scored
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.2.5
    - 2.2.7
    - 2.2.9
    - 2.2.11
    - 2.2.12
    - 2.2.13

- name: Comment out "start" line in {{ svc_item.script }}
  lineinfile:
    path:   "{{ svc_item.script }}"
    regexp: '^start on (.*)'
    line:   '#start on \1'
    backrefs: yes
  when: svc_item.cis_id not in os_hardening_exclusions and svc.stat.exists
  tags:
    - scored
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.2.5
    - 2.2.7
    - 2.2.9
    - 2.2.11
    - 2.2.12
    - 2.2.13

- name: Stop {{ svc_item.name }}
  service:
    name:  "{{ svc_item.name }}"
    state: stopped
  when: svc_item.cis_id not in os_hardening_exclusions and svc.stat.exists
  tags:
    - scored
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.2.5
    - 2.2.7
    - 2.2.9
    - 2.2.11
    - 2.2.12
    - 2.2.13
